name: Build and Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    
    steps:
      - uses: actions/checkout@b4ffde65f46336ab11de5bde24cb271040c9f104 # v4.1.1

      - name: Install dependencies (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install -y build-essential pkg-config libgtk-3-dev libhpdf-dev

      - name: Set up MSYS2 (Windows)
        if: matrix.os == 'windows-latest'
        uses: msys2/setup-msys2@fb197b72ce45fb24f17bf3f807a388985654d1f2 # v2
        with:
          update: true
          install: >-
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-gtk3
            pkg-config
            make
            mingw-w64-ucrt-x86_64-libharu
          msystem: MINGW64

      - name: Run tests (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: make test

      - name: Build (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: make release

      - name: Package Application (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          tar -czvf HardStress-linux.tar.gz HardStress

      - name: Upload Linux Artifact
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: HardStress-linux
          path: HardStress-linux.tar.gz

      - name: Run tests (Windows)
        if: matrix.os == 'windows-latest'
        shell: msys2 {0}
        run: make test

      - name: Build (Windows)
        if: matrix.os == 'windows-latest'
        shell: msys2 {0}
        run: |
          make release CC=x86_64-w64-mingw32-gcc

      - name: Package Application (Windows)
        if: matrix.os == 'windows-latest'
        shell: msys2 {0}
        run: |
          set -e
          ARTIFACT_DIR="HardStress-windows"
          mkdir $ARTIFACT_DIR
          mv HardStress.exe $ARTIFACT_DIR/
          
          ldd $ARTIFACT_DIR/HardStress.exe | grep -o '/mingw64/bin/[^ ]*\.dll' | sort -u | xargs -I{} cp {} $ARTIFACT_DIR/
          
          echo "DLLs empacotadas com sucesso."

      - name: Create Zip Archive (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          Compress-Archive -Path HardStress-windows -DestinationPath HardStress-windows.zip

      - name: Upload Windows Artifact
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: HardStress-windows
          path: HardStress-windows.zip
          
  release:
    needs: [build]
    runs-on: ubuntu-latest
    # Adicionado bloco de permissões para permitir que o job crie/modifique releases.
    permissions:
      contents: write
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
        with:
          path: artifacts

      - name: Create Release
        uses: softprops/action-gh-release@6cbd405e2c4e67a21c47fa9e383d020e4e28b836 # v2.3.3
        with:
          files: |
            artifacts/HardStress-windows/HardStress-windows.zip
            artifacts/HardStress-linux/HardStress-linux.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
