name: Build and Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install -y build-essential pkg-config libgtk-3-dev

      - name: Set up MSYS2 (Windows)
        if: matrix.os == 'windows-latest'
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-gtk3
            pkg-config
          msystem: MINGW64

      - name: Build (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: make release

      - name: Build (Windows)
        if: matrix.os == 'windows-latest'
        shell: msys2 {0}
        run: |
          make release CC=x86_64-w64-mingw32-gcc TARGET=HardStress.exe

      - name: Package Application (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          tar -czvf HardStress-linux.tar.gz HardStress

      - name: Upload Linux Artifact
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v4
        with:
          name: HardStress-linux
          path: HardStress-linux.tar.gz

      - name: Package Application (Windows)
        if: matrix.os == 'windows-latest'
        shell: msys2 {0}
        run: |
          set -e
          ARTIFACT_DIR="HardStress-windows"
          mkdir $ARTIFACT_DIR
          mv HardStress.exe $ARTIFACT_DIR/
          
          # Usa ldd para encontrar e copiar todas as dependências .dll necessárias
          # O grep filtra para pegar apenas as bibliotecas do ambiente mingw64
          ldd $ARTIFACT_DIR/HardStress.exe | grep -o '/mingw64/bin/[^ ]*\.dll' | sort -u | xargs -I{} cp {} $ARTIFACT_DIR/
          
          echo "DLLs empacotadas com sucesso."

      - name: Create Zip Archive (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          Compress-Archive -Path HardStress-windows -DestinationPath HardStress-windows.zip

      - name: Upload Windows Artifact
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v4
        with:
          name: HardStress-windows
          path: HardStress-windows.zip
          
  release:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/*/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
