name: Build and Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential pkg-config libgtk-3-dev

      - name: Build
        run: make release

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: HardStress-linux
          path: HardStress

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up MSYS2
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-gtk3
            pkg-config
          msystem: MINGW64

      - name: Build
        shell: msys2 {0}
        run: |
          make release CC=x86_64-w64-mingw32-gcc TARGET=HardStress.exe

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: HardStress-windows
          path: HardStress.exe

  release:
    needs: [build-linux, build-windows]
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
